version: '3.3'
services:
  mongo:
    image: mongo:4.4.6
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - '27018:27017'
    volumes:
      - ./data/dev/mongo:/data/db
  mongo-seed:
    build:
      context: ./doc/mongo_seed
      dockerfile: Dockerfile
      args:
          - DATABASE_URI=mongodb://user:pass@mongo:27017/mezink?authSource=admin
          - USERNAME=user
          - PASSWORD=pass
    depends_on:
        - mongo
  api:
    build: .
    ports:
      - '8080'
    volumes:
      - .:/app
    depends_on:
      - 'mongo'
  web:
    container_name: 'web'
    image: 'nginx:latest'
    ports:
      - '8080:80'
    volumes:
      - ./nginx/dev.conf.d:/etc/nginx/conf.d
    depends_on:
      - 'api'