version: '3.3'
services:
  mongo:
    image: mongo:4.4.6
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - '27018:27017'
    volumes:
      - ./data/dev/mongo:/data/db
    networks:
      - dba
  api:
    build: .
    ports:
      - '8080'
    volumes:
      - .:/app
    depends_on:
      - 'mongo'
  web:
    container_name: 'web'
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./nginx/dev.conf.d:/etc/nginx/conf.d
    depends_on:
      - 'api'
networks:
  dba: